### ISSUE TITLE
stage channel bugs

### ISSUE THREAD

**Issue by zapteryx** [ZapSquared/Quaver#40]
there's currently a ton of bugs surrounding stage channels, namely with lacking permissions and stuff
leave some steps to reproduce bugs here and i'll try to fix it

**Comment by Xayanide** [comment]
**Describe the bug**
When using the play command on stage channels, the bot adds a track to the queue but crashes before the track got added to the queue.

Reproducible if:

- Quaver do not have any Administrator permissions on any of its roles or to itself.

**To Reproduce**
Steps to reproduce the behavior:
1. Don't give any roles that has Administrator permission at Quaver. Don't give Administrator permission to @everyone
2. On stage channels settings, untick View channel permission that directs at Quaver.
2. On stage channels settings, untick View channel permission @everyone
3. Connect to the stage channel and use the play command as usual.
4. See error on console:
Encountered error with command play
TypeError: Cannot read property 'type' of null
    at Object.execute (/home/runner/azdela/commands/play.js:136:21)
    at async Client.<anonymous> (/home/runner/azdela/main.js:201:4)

**Expected behavior**
Should be playing as expected like on voice channels.
Should be checking permissions properly and prompt that it does not have it.

**Comment by zapteryx** [comment]
for now it appears that the stage channel issues have been resolved. create a new issue if you encounter any issues.
