### ISSUE TITLE
Locales not working in console logs and in slash command descriptions.

### ISSUE THREAD

**Issue by Xayanide** [ZapSquared/Quaver#57]
**Describe the bug**
If switching to a differnt locale, the console logs and the descriptions of slash commands still remain in the en-US language.

**To Reproduce**
1. Use Quaver's locale command.
2. Switch to a different locale.

**Expected behavior**
Console logs and the descriptions in slash commands should change to the specified locale.

**Comment by zapteryx** [comment]
so the 2 issues we currently face are this:
- the locale command affects server locale, which should theoretically update the slash command description, but since slash commands are defined globally, we can't really do that
- for logging purposes, it uses locale specified in settings.json, which should make sense since it's for the bot owner.
both the slash command descriptions and log messages are currently controlled by settings.json, but I'm hoping someday it'll be possible to have per-server slash command descriptions.

**Comment by zapteryx** [comment]
closing for now, if this isn't a limitation in the future, i'll re-open
